"""
ESP32 C/C++ Header Generator module for Fusion 360 Kinematics Exporter.
"""

import datetime
import re
from . import RobotModel, DHParameter, KinematicChain

def _sanitize_name(name: str) -> str:
    """Make C identifier names from chain names (replace spaces/hyphens with underscores, lowercase)."""
    clean_name = re.sub(r'[\s\-]+', '_', name)
    return clean_name.lower()

def _format_dh_table(chain_name: str, convention: str, dh_params: list[DHParameter]) -> str:
    """Format a DH parameters table."""
    lines = []
    lines.append(f"static const dh_param_t {chain_name}_{convention}_dh[] = {{")
    lines.append("    /* name,              type,             a,       alpha,    d,       theta_off, min,     max */")
    
    for dh in dh_params:
        joint_type_str = "JOINT_REVOLUTE" if dh.joint_type == "revolute" else "JOINT_PRISMATIC"
        
        lines.append(
            f'    {{ "{dh.joint_name}", {joint_type_str:>14}, '
            f'{dh.a:>7.3f}f, {dh.alpha:>7.4f}f, {dh.d:>7.3f}f, '
            f'{dh.theta_offset:>7.4f}f, {dh.limit_min:>7.4f}f, {dh.limit_max:>7.4f}f }},'
        )
        
    lines.append("};")
    return "\n".join(lines)

def generate_header(robot_model: RobotModel, filepath: str) -> None:
    """Generate a C/C++ header file with DH parameter tables for ESP32 firmware."""
    date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Pre-process chains and tables
    chains_c_code = []
    dh_tables_standard = []
    dh_tables_modified = []
    
    for chain in robot_model.chains:
        safe_chain_name = _sanitize_name(chain.name)
        
        # Standard DH
        dh_tables_standard.append(f"/* Chain: {chain.name} (Standard DH) */\n" + 
                                  _format_dh_table(safe_chain_name, "standard", chain.dh_standard))
                                  
        # Modified DH
        dh_tables_modified.append(f"/* Chain: {chain.name} (Modified DH) */\n" + 
                                  _format_dh_table(safe_chain_name, "modified", chain.dh_modified))
                                  
        # Chain struct entry
        num_joints = len(chain.dh_standard)
        chains_c_code.append(
            f'    {{ "{chain.name}", {num_joints}, '
            f'{safe_chain_name}_standard_dh, {safe_chain_name}_modified_dh }},'
        )
        
    # Build full header content
    content = f"""/**
 * @file robot_kinematics.h
 * @brief Auto-generated DH parameters for {robot_model.name}
 * @note Generated by Fusion 360 Kinematics Exporter
 * @date {date_str}
 * 
 * Units: meters (m) and radians (rad)
 */

#pragma once

#ifndef ROBOT_KINEMATICS_H
#define ROBOT_KINEMATICS_H

#include <stdint.h>
#include <math.h>

/* ===== Type Definitions ===== */

typedef enum {{
    JOINT_REVOLUTE  = 0,
    JOINT_PRISMATIC = 1
}} joint_type_t;

typedef enum {{
    DH_STANDARD = 0,
    DH_MODIFIED = 1
}} dh_convention_t;

typedef struct {{
    const char* name;          /**< Joint name */
    joint_type_t type;         /**< Joint type */
    float a;                   /**< Link length (m) */
    float alpha;               /**< Link twist (rad) */
    float d;                   /**< Link offset (m) */
    float theta_offset;        /**< Joint angle offset (rad) */
    float min_limit;           /**< Lower position limit */
    float max_limit;           /**< Upper position limit */
}} dh_param_t;

typedef struct {{
    const char* name;          /**< Chain name */
    uint8_t num_joints;        /**< Number of joints in chain */
    const dh_param_t* standard_dh;  /**< Standard DH parameters */
    const dh_param_t* modified_dh;  /**< Modified DH (Craig) parameters */
}} kinematic_chain_t;

/* ===== Robot Configuration ===== */

#define ROBOT_NAME "{robot_model.name}"
#define NUM_CHAINS {len(robot_model.chains)}

/* ===== Standard DH Parameters ===== */
// T_i = Rz(theta) * Tz(d) * Tx(a) * Rx(alpha)

{chr(10).join(dh_tables_standard)}

/* ===== Modified DH Parameters (Craig Convention) ===== */
// T_i = Rx(alpha_{{i-1}}) * Tx(a_{{i-1}}) * Rz(theta_i) * Tz(d_i)

{chr(10).join(dh_tables_modified)}

/* ===== Chain Definitions ===== */

static const kinematic_chain_t robot_chains[] = {{
{chr(10).join(chains_c_code)}
}};

/* ===== Forward Kinematics Helper (Standard DH) ===== */

static inline void dh_transform_standard(
    const dh_param_t* dh, float q, float T[4][4]
) {{
    float theta = (dh->type == JOINT_REVOLUTE) ? (q + dh->theta_offset) : dh->theta_offset;
    float d_val = (dh->type == JOINT_PRISMATIC) ? (q + dh->d) : dh->d;
    float ct = cosf(theta), st = sinf(theta);
    float ca = cosf(dh->alpha), sa = sinf(dh->alpha);

    T[0][0] = ct;     T[0][1] = -st*ca;  T[0][2] = st*sa;   T[0][3] = dh->a * ct;
    T[1][0] = st;     T[1][1] = ct*ca;   T[1][2] = -ct*sa;  T[1][3] = dh->a * st;
    T[2][0] = 0.0f;   T[2][1] = sa;      T[2][2] = ca;      T[2][3] = d_val;
    T[3][0] = 0.0f;   T[3][1] = 0.0f;    T[3][2] = 0.0f;    T[3][3] = 1.0f;
}}

/* ===== Forward Kinematics Helper (Modified DH / Craig) ===== */

static inline void dh_transform_modified(
    const dh_param_t* dh, float q, float T[4][4]
) {{
    float theta = (dh->type == JOINT_REVOLUTE) ? (q + dh->theta_offset) : dh->theta_offset;
    float d_val = (dh->type == JOINT_PRISMATIC) ? (q + dh->d) : dh->d;
    float ct = cosf(theta), st = sinf(theta);
    float ca = cosf(dh->alpha), sa = sinf(dh->alpha);

    T[0][0] = ct;        T[0][1] = -st;       T[0][2] = 0.0f;   T[0][3] = dh->a;
    T[1][0] = st*ca;     T[1][1] = ct*ca;     T[1][2] = -sa;    T[1][3] = -d_val*sa;
    T[2][0] = st*sa;     T[2][1] = ct*sa;     T[2][2] = ca;     T[2][3] = d_val*ca;
    T[3][0] = 0.0f;      T[3][1] = 0.0f;      T[3][2] = 0.0f;   T[3][3] = 1.0f;
}}

/* ===== Chain FK: Compute end-effector pose ===== */

static inline void chain_fk(
    const kinematic_chain_t* chain, const float* q, 
    dh_convention_t convention, float T_out[4][4]
) {{
    // Initialize as identity
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            T_out[i][j] = (i == j) ? 1.0f : 0.0f;

    const dh_param_t* params = (convention == DH_STANDARD) 
        ? chain->standard_dh : chain->modified_dh;

    for (uint8_t i = 0; i < chain->num_joints; i++) {{
        float T_joint[4][4];
        if (convention == DH_STANDARD)
            dh_transform_standard(&params[i], q[i], T_joint);
        else
            dh_transform_modified(&params[i], q[i], T_joint);

        // T_out = T_out * T_joint
        float T_temp[4][4];
        for (int r = 0; r < 4; r++)
            for (int c = 0; c < 4; c++) {{
                T_temp[r][c] = 0.0f;
                for (int k = 0; k < 4; k++)
                    T_temp[r][c] += T_out[r][k] * T_joint[k][c];
            }}
        for (int r = 0; r < 4; r++)
            for (int c = 0; c < 4; c++)
                T_out[r][c] = T_temp[r][c];
    }}
}}

#endif /* ROBOT_KINEMATICS_H */
"""
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
